spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 0ms
    jedis:
      pool:
        max-active: 10 #最大连接数
        max-wait: 1ms #最大等待数
        max-idle:   5 #连接池的最大空闲时间
        min-idle:   0 #连接池的最小空闲时间