spring:
  data:
    mongodb:
      database: 0
      #host: 127.0.0.1
      #port: 27017
      username:
      password:
      uri: mongodb: //localhost:27017/Mall-Shop
      repositories:
        type: auto